### PR TITLE
#63 support non-utf encoding

### PR DESCRIPTION
**Pull request by spacemansteve**
reading files is more complicated now.  some files don't contain an encoding so we try reading with utf-8.  if that doesn't work, they file probably has a non utf-8 encoding so we read it without an encoding

### CODE REVIEW

**Comment by romanchyla** [comment]
how about detecting the encoding= attribute? http://code.activestate.com/recipes/363841-detect-character-encoding-in-an-xml-file/

**Comment by aaccomazzi** [comment]
Is it necessary to try and read as utf-8 first?  Since we are passing the buffer to an XML parser, I assume it would figure out the encoding itself anyway, so I'd just read as bytes and pass it along...

**Comment by spacemansteve** [comment]
If we do not try to read with utf-8 several unit tests fail.  I assume the tests mimic data files where the encoding is not in the file and needs to be provided.

**Review by marblestation — COMMENTED** [review]
Same comment as Alberto, could we try directly without specifying utf-8 or there is a motivation for doing it this way? If there is, may be we could add a comment on that part of the code so that we will remember.

**Comment by aaccomazzi** [comment]
@romanchyla since we parse the stream using a Beautifusoup parser and that in turns used a utility to detect the encoding (see https://www.crummy.com/software/BeautifulSoup/bs4/doc/#encodings) I think we should not need to do additional detective work based on the docs.

**Comment by romanchyla** [comment]
@aaccomazzi i don't see beautifulsoup used in the part that Steve changed; only codecs.open()

hardcoding utf-8 (or leaving it empty; which actually relies on the default set by locales) is not going to be future-proof

so let's use BeautifulSoup everywhere

**Pull request closed without merging**
