### PR TITLE
Add TEI XML parser for Grobid output files

### PR DESCRIPTION
**Pull request by aaccomazzi**
Cleaned up other minor issues.

### CODE REVIEW

**Comment by jonnybazookatone** [comment]
Can you look into why the tests fail? Otherwise it can be merged.

**Comment by aaccomazzi** [comment]
I have no idea why the tests fail, but they are also failing in the current release (see travis report).  I'm pretty sure the things I modified do pass all tests in tests/test_unit/test.py.  Maybe you have made some mods but not pushed them to github?

**Comment by jonnybazookatone** [comment]
Oh yeah, I didn't see the main build is failing. I'll take a look.

**Comment by jonnybazookatone** [comment]
I take that back. It was passing on the last build. Maybe some dependencies got updated recently that is causing issues.

**Comment by jonnybazookatone** [comment]
Go ahead and merge. It's something with the functional tests, and most likely they updated rabbit on travis or something.

**Pull request merged**
