### PR TITLE
Fix encoding declaration error

### PR DESCRIPTION
**Pull request by krisbukovi**
To fix "Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration" errors (see 2011AcGeo..59..657T for example). Unit test added to assert this error is not thrown when using this non-standard parsing that occurs if all parsers fail.

### CODE REVIEW

**Review by marblestation — APPROVED** [review]
Nice! This should work for most cases, we need to dig deeper and understand why non of the previous parsers worked (it could be that this last one also doesn't work) and what happens if in the document header it says it is not UTF-8?
```
<?xml version="1.0" encoding="iso-8859-1"?>                                           
```
Then, given what you have discovered here, could you check if this can also needs to be applied to this section of the code? https://github.com/adsabs/ADSfulltext/blob/628c05a30f8cf1b92ec5d333b4254e27f1518552/adsft/extraction.py#L185-L189
In any case, you can go ahead and merge this and open issues in github or new PR for my comments above.

**Comment by krisbukovi** [comment]
So if you modify my unit test you'll see that the reason the other parsers didn't work is that there is no text to extract within the body tag, so when we check if it was successful it will always be false for these articles because we're extracting an empty body tag. 

As for how this issue was addressed, we could have also removed the encoding declaration with regex to avoid this error. Both methods seemed comparable so I just chose the one that I thought would be more understandable later on, but I have no strong opinion on one or the other.  

HTML shouldn't have this issue because it doesn't have the encoding declaration, but I'll double check. 

Thanks!

**Comment by krisbukovi** [comment]
Oh and I forgot to address the question "and what happens if in the document header says it is not UTF-8?" The error is thrown no matter the type of encoding specified in the declaration.

The string that's being passed into document_fromstring() is unicode since in open_xml() we decode it using the detected encoding, so converting it to bytecode with .encode('utf-8') shouldn't have any consequences.

**Comment by marblestation** [comment]
Thanks! I better understand the problem now, it is not just an encoding problem but a failure to detect that the previous parser have actually worked. The document really does not have body content, so the correct output is an empty fulltext field. With our current implementation, we would end up with the full xml (without the tags, thus the tittle, authors, affiliations...) in the body solr field despite that the xml document was well formatted and it had an empty body.

Can we get from the logs how many documents show the `Parsing XML in non-standard way` log message? From those, can we check them (or a random sample if it's too large) to see how many do really have empty bodies? Depending on what we find, I would be incline to change our current implementation by: iterate through all the parsers (as we do now) and if all fail, let the body be empty and not use that "non-standard way". This can be a separate PR, since this PR is still valid as it is addressing an encoding issue.

**Comment by marblestation** [comment]
I created an issue for that last comment: https://github.com/adsabs/ADSfulltext/issues/101

**Pull request merged**
