### PR TITLE
Added diagnostics flag

### PR DESCRIPTION
**Pull request by marblestation**
- No data will be saved in diagnostics mode
- Detailed execution information will be printed to stdout

### CODE REVIEW

**Comment by marblestation** [comment]
BTW, I also fixed a bug in run.py that prevented from actually calling the extraction tasks.

**Comment by romanchyla** [comment]
I like your idea, how about if we push it little bit farther? (actually, I think you proposed it yourself)

```
def show_diagnostics():
    from mock import mock #keep it here, mock is only installed with dev-requirements.txt
    with mock.patch.object(tasks.task_extract, 'delay') as extractor, \
           mock.patch.object(tasks.writer, 'write_content') as writer:
           tasks.task_check_if_extract(message)

           print 'extractor produced', extractor.args
           print 'writer would have written', writer.args
```

and the print statemtns - we should turn them into logger.debug() - and have them always on; but it ism important to use the following form:

```
logger.debug('message a=%s', a)
```

which means we could remove the diagnostics=False kwarg and simplify somewhat (it is a global switch anyways)

**Comment by marblestation** [comment]
But with this new approach, task_extract will never get executed and we won't show diagnostics further down in the execution chain. The actual chain is:

```
task_check_if_extract => task_extract => {write_content, task_output_results} => app.forward_message
```

Of course, we could repeat that mocking and calling for every task, but I think it is good that we don't duplicate that and go throw the real flow so that the diagnostics always reflect what will be executed in a real scenario. Wasn't that the original idea or I misinterpreted it?

Regarding using the logger, I thought we also agreed to use prints for the diagnostics via slack. Should we change this criteria then?

**Comment by romanchyla** [comment]
I realize I haven't been clear (and to be fair: there is a subtle semantic difference in play here)

when i first wrote the diagnostics function, it was meant as a quick 'sanity check' - to see everything is working (so the function itself prints to stdout - so that operator doesn't need to tail logs)

besides that, everything else should use loggers (and we should add more logging statements in general; hence I propose to keep the diagnostic messages in the code by default - and see them only with appropriate DEBUG level)

you are right the task_extract wouldn't be called - unless we call it ourselves - intuitively I'm going for just that; I want to be able to verify that the queue is working without having to think too hard. so that was the original intent

see an example here:

https://github.com/adsabs/ADSOrcid/blob/master/run.py#L262

you can call 'python run.py -d' and it will pick an orcid/bibcode for you and show what happens

**Pull request merged**
